name: "Test Exec Action"
description: "Set up a Remote Docker Context over SSH using Password or Keyfile Authentication"

inputs:
  testing:
    description: "Testing Input"
    required: true
    default: "HELLO WORLD"
  host:
    description: "Docker Host"
    required: true
  port:
    description: "Docker Port"
    required: true
    default: "22"
  user:
    description: "Docker User"
    required: true
  pass:
    description: "SSH Password"
  ssh_key:
    description: "SSH Key File"
  registry_user:
    description: "Registry Auth Username"
  registry_pass:
    description: "Registry Auth Password"
  registry_host:
    description: "Registry Auth Hostname"

#runs:
#  using: "composite"
#  steps:
#    - name: "Setup SSH"
#      if: ${{ inputs.pass != '' || inputs.ssh_key != '' }}
#      shell: bash
#      run: source ${GITHUB_ACTION_PATH}/src/ssh.sh
#    - name: "Docker Context"
#      shell: bash
#      run: source ${GITHUB_ACTION_PATH}/src/context.sh
#    - name: "Docker Login"
#      if: ${{ inputs.registry_user != '' }}
#      shell: bash
#      run: source ${GITHUB_ACTION_PATH}/src/login.sh
#    # TODO: This is not possible in composite because there is no POST
#    - name: "SSH Cleanup"
#      if: ${{ env.STATE_SSH_CLEANUP != '' }}
#      shell: bash
#      run: source ${GITHUB_ACTION_PATH}/src/cleanup.sh

runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
